### ISSUE TITLE
Design palette of colours / style of components

### ISSUE THREAD

**Issue by ppadamczyk** [ppadamczyk/Gardenflow#14]

**Comment by cysi4k** [comment]
Proposition 1:
![61474869_433425640809535_946388089394167808_n](https://user-images.githubusercontent.com/26000448/58477698-79ab0d80-8154-11e9-8be2-ede29e9d9fb8.png)

**Comment by cysi4k** [comment]
Proposition 2:
![61735983_615628992275505_7314984386384887808_n](https://user-images.githubusercontent.com/26000448/58477799-be36a900-8154-11e9-8a7c-f0e9a738c8a1.png)

**Comment by cysi4k** [comment]
Proposition 3:
![image](https://user-images.githubusercontent.com/26000448/58478409-53866d00-8156-11e9-95de-19dfec2dc256.png)
